--[[
	A camera controller with many functions for different camera effects.
]]

-- SERVICES --
-- local ReplicatedStorage = game:GetService("ReplicatedStorage")
-- local RunService = game:GetService("RunService")
-- local TweenService = game:GetService("TweenService")
-- local Players = game:GetService("Players")

-- VARIABLES --
local controller = {}
-- local camera = workspace.CurrentCamera
-- local player = Players.LocalPlayer

function controller.focusOnPoint(point: CFrame)
	
end

function controller.orbitAroundPoint(centerPoint)
	
end

return controller